// 带知识库的假秒懂（spec 3a §2.1、§2.2、§2.3）。读接口按真实行为返回，并复现 §2.2 的坑：
//   /qa/list 的 filterType 传字符串时只回未审核的（不报错）；段落列表缺 knowledgeBaseId 回 400；
//   相似度检查回 qaId；语义搜索不含未审核的，而且只返回相似度 0.8 以上的（§2.3，09-25 实测）；
//   语义搜索一行一个向量，同一条 FAQ 可能占好几行（09-25 真机验收）。
// 读接口清单之外的请求都走 404，unexpected() 把它们列出来：测试断言它为空，保证 md kb 只读。
// state.faqs 可以在测试中途改（模拟「执行之后知识库改过」）。
import { ok, startFakeMiaodong } from './fake-miaodong.mjs';
import { EXEC_BOT } from './exec-fixtures.mjs';
import { faqs, files, kbCanvas, kbList, paragraphs, semanticRows, sim } from './kb-fixtures.mjs';

const SEMANTIC_FLOOR = 0.8;
const bad = (message) => ({ status: 400, body: { statusCode: 400, message, error: 'Bad Request' } });

// semanticFail：语义搜索回 502（模拟秒懂那边出错，md 不能把它当成「没有结果」）；
// omitFaqFields：FAQ 的返回里去掉这些字段（模拟接口改名）；overlap：第 2 页起往回多给几条（模拟翻页不稳：条数对得上，却有重复、有漏的）
export async function startKbServer({ details = {}, pageCap = Infinity, kbs = kbList(), faqRows = faqs(), semanticFail = false, omitFaqFields = [], overlap = 0 } = {}) {
  const state = { faqs: faqRows };
  const page = (rows, current, pageSize) => {
    const size = Math.min(Number(pageSize) || 20, pageCap);
    const c = Number(current) || 1;
    const start = Math.max(0, (c - 1) * size - (c > 1 ? overlap : 0));
    return ok(rows.slice(start, start + size), { page: { current: c, pageSize: size, total: rows.length } });
  };
  const omit = (row) => {
    for (const k of omitFaqFields) delete row[k];
    if (omitFaqFields.includes('isReviewed')) delete row.reviewed;
    return row;
  };
  const faqOut = (f, extra = {}) => omit({
    id: f.id, question: f.question, answer: f.answer, isReviewed: f.isReviewed, isAutogenerated: false,
    duplicateStatus: f.duplicateStatus ?? 'normal', materials: [], mhMaterialIds: [], tags: [], ...extra,
  });
  const routes = {
    'GET /api/bot/list': ({ query }) => ok(query.orgId === 'org-1' ? [{ id: EXEC_BOT, name: '太极2.0 质检革新版' }] : []),
    'GET /api/canvas/get': () => ok({ canvasId: 'main-1', rawCanvas: kbCanvas(), version: 'v1.0.403', updatedAt: '2026-09-24T01:00:00.000Z' }),
    'GET /api/canvas/list-version': () => ok([{ canvasId: 'ver-402', version: 'v1.0.402', name: '402', versionType: 'online' }]),
    'GET /api/canvas/history/details': ({ query }) => (details[query.execId]
      ? ok(details[query.execId])
      : { status: 201, body: { code: -1, message: 'CANVAS_EXEC_NOT_FOUND' } }),
    'GET /api/knowledge-base/list': ({ query }) => page(kbs, query.current, query.pageSize),
    'GET /api/knowledge-base/details': ({ query }) => {
      const k = kbs.find((x) => x.id === query.knowledgeBaseId);
      return k
        ? ok({ knowledgeBaseId: k.id, name: k.name, qaCount: k.qaCount, docCount: k.fileCount, webCount: k.pageCount, videoCount: k.videoCount, embeddingModel: k.modelType })
        : bad('knowledge base not found');
    },
    'GET /api/qa/metrics': ({ query }) => {
      const rows = state.faqs.filter((f) => f.kb === query.knowledgeBaseId);
      return ok({ total: rows.length, reviewed: rows.filter((f) => f.isReviewed).length, unreviewed: rows.filter((f) => !f.isReviewed).length });
    },
    'POST /api/qa/list': ({ body }) => {
      if (body.filterType === undefined || body.sortType === undefined) {
        return bad('filterType must be one of the following values: ALL, REVIEWED, GENERATED, 0, 1, 2');
      }
      if (!kbs.some((k) => k.id === body.knowledgeBaseId)) return bad('knowledge base not found');
      if (semanticFail && body.searchMode === 'semantic') return { status: 502, body: { statusCode: 502, message: 'Bad Gateway' } };
      let rows = state.faqs.filter((f) => f.kb === body.knowledgeBaseId);
      if (typeof body.filterType === 'string') rows = rows.filter((f) => !f.isReviewed); // 真实服务端的坑：传字符串一律只回未审核的
      else if (body.filterType === 1) rows = rows.filter((f) => f.isReviewed);
      else if (body.filterType === 2) rows = rows.filter((f) => !f.isReviewed);
      let out = rows.map((f) => faqOut(f));
      if (body.sortType === 'SIMILARITY' && body.keyword) {
        out = body.searchMode === 'text'
          ? rows.filter((f) => f.question.includes(body.keyword) || f.answer.includes(body.keyword)).map((f) => faqOut(f))
          : semanticRows(rows, body.knowledgeBaseId, body.keyword, SEMANTIC_FLOOR).map(({ f, score }) => faqOut(f, { similarity: score }));
      }
      return page(out, body.current, body.pageSize);
    },
    'POST /api/qa/check-similarity': ({ body }) => (!kbs.some((k) => k.id === body.knowledgeBaseId) ? bad('knowledge base not found') : ok(state.faqs
      .filter((f) => f.kb === body.knowledgeBaseId)
      .map((f) => omit({ qaId: f.id, question: f.question, answer: f.answer, similarity: sim(body.question, f.question), reviewed: f.isReviewed, materials: [], mhMaterialIds: [] }))
      .filter((f) => f.similarity >= 0.5)
      .sort((a, b) => b.similarity - a.similarity))),
    'GET /api/knowledge-base/file/list': ({ query }) => page(
      files().filter((f) => f.kb === query.knowledgeBaseId).map(({ kb, paragraphCount, ...f }) => ({ ...f, createAt: 0, createBy: 'u', tags: [] })),
      query.current, query.pageSize,
    ),
    'GET /api/knowledge-base/file/details': ({ query }) => {
      const f = files().find((x) => String(x.id) === String(query.docId) && x.kb === query.knowledgeBaseId);
      return f
        ? ok({ id: f.id, name: f.name, status: f.status, extension: f.extension, paragraphCount: f.paragraphCount, docUrl: 'https://example.com/a.pdf', abstract: '', tags: [] })
        : bad('doc not found');
    },
    'GET /api/knowledge-base/file/paragraphs': ({ query }) => {
      if (!query.knowledgeBaseId) return bad('knowledgeBaseId must be a string');
      if (!/^\d+$/.test(String(query.id ?? ''))) return bad('id must be a number string');
      const rows = paragraphs().filter((p) => String(p.fileId) === query.id).map(({ fileId, ...p }) => ({ ...p, createdAt: 0 }));
      return page(rows, query.current, query.pageSize);
    },
    'GET /api/knowledge-base/web/list': ({ query }) => page([], query.current, query.pageSize),
  };
  const server = await startFakeMiaodong(routes);
  const reads = new Set(Object.keys(routes));
  return Object.assign(server, { state, unexpected: () => server.requests.filter((r) => !reads.has(`${r.method} ${r.path}`)) });
}
