// 带知识库的假秒懂（spec 3a §2.1、§2.2、§2.3；3b §2.1、§8）。读接口按真实行为返回，并复现 3a §2.2 的坑：
//   /qa/list 的 filterType 传字符串时只回未审核的（不报错）；段落列表缺 knowledgeBaseId 回 400；
//   相似度检查回 qaId；语义搜索不含未审核的，而且只返回相似度 0.8 以上的（§2.3，09-25 实测）；
//   语义搜索一行一个向量，同一条 FAQ 可能占好几行（09-25 真机验收）。
// FAQ、文件、段落都放在 state 里，读写共用；测试中途可以改（模拟「执行之后知识库改过」「预演之后有人改了」）。
// writable：打开 3b 的写接口，行为照 09-25 从控制台前端代码核对的来（3b §2.1）：新建不返回 id；新 FAQ 默认未审核；
//   新段落先是 processing，被读 readyAfter 次之后变 ready；原文件从 /files/... 下载。
// failOn：{ 'POST /api/qa/batch-create': [2, { n: 3, applied: true }] }——第 2 次调用直接回 502；第 3 次先写进去再回 502（回复丢了）。
// mangle：写进去的问题、答案、段落先经过它（模拟服务端改了内容，读回来和写的不一样）。
// 路由清单之外的请求都走 404，unexpected() 把它们列出来；writes() 列出全部写请求。
import { ok, startFakeMiaodong } from './fake-miaodong.mjs';
import { EXEC_BOT } from './exec-fixtures.mjs';
import { faqs, files, kbCanvas, kbList, paragraphs, semanticRows, sim } from './kb-fixtures.mjs';

const SEMANTIC_FLOOR = 0.8;
const bad = (message) => ({ status: 400, body: { statusCode: 400, message, error: 'Bad Request' } });
const gateway = { status: 502, body: { statusCode: 502, message: 'Bad Gateway' } };

// semanticFail：语义搜索回 502（模拟秒懂那边出错，md 不能把它当成「没有结果」）；
// omitFaqFields：FAQ 的返回里去掉这些字段（模拟接口改名）；overlap：第 2 页起往回多给几条（模拟翻页不稳：条数对得上，却有重复、有漏的）
export async function startKbServer({
  details = {}, pageCap = Infinity, kbs = kbList(), faqRows = faqs(), semanticFail = false, omitFaqFields = [], overlap = 0,
  fileRows = files(), paragraphRows = paragraphs(), writable = false, readyAfter = 1, failOn = {}, bots = null, mangle = (s) => s,
} = {}) {
  const state = {
    faqs: faqRows,
    files: fileRows.map((f) => ({ tags: [], abstract: '', original: `${f.name} 的原文件内容`, ...f })),
    paragraphs: paragraphRows.map((p) => ({ ...p })),
    nextFaqId: 90001,
    nextDocId: 9001,
    nextParaId: 99001,
    calls: {},
  };
  let origin = '';
  const page = (rows, current, pageSize) => {
    const size = Math.min(Number(pageSize) || 20, pageCap);
    const c = Number(current) || 1;
    const start = Math.max(0, (c - 1) * size - (c > 1 ? overlap : 0));
    return ok(rows.slice(start, start + size), { page: { current: c, pageSize: size, total: rows.length } });
  };
  const omit = (row) => {
    for (const k of omitFaqFields) delete row[k];
    if (omitFaqFields.includes('isReviewed')) delete row.reviewed;
    return row;
  };
  const faqOut = (f, extra = {}) => omit({
    id: f.id, question: f.question, answer: f.answer, isReviewed: f.isReviewed, isAutogenerated: false,
    duplicateStatus: f.duplicateStatus ?? 'normal', materials: f.materials ?? [], mhMaterialIds: f.mhMaterialIds ?? [], tags: [], ...extra,
  });
  const hasKb = (id) => kbs.some((k) => k.id === id);
  const filesOf = (kb) => state.files.filter((f) => f.kb === kb);
  const parasOf = (docId) => state.paragraphs.filter((p) => String(p.fileId) === String(docId)).sort((a, b) => a.index - b.index);
  const docUrl = (f) => (f.manual ? '' : `${origin}/files/${f.id}/${encodeURIComponent(f.name)}`);
  const botList = bots ?? [{ id: EXEC_BOT, name: '太极2.0 质检革新版' }];

  const routes = {
    'GET /api/bot/list': ({ query }) => ok(query.orgId === 'org-1' ? botList : []),
    'GET /api/canvas/get': () => ok({ canvasId: 'main-1', rawCanvas: kbCanvas(), version: 'v1.0.403', updatedAt: '2026-09-24T01:00:00.000Z' }),
    'GET /api/canvas/list-version': () => ok([{ canvasId: 'ver-402', version: 'v1.0.402', name: '402', versionType: 'online' }]),
    'GET /api/canvas/history/details': ({ query }) => (details[query.execId]
      ? ok(details[query.execId])
      : { status: 201, body: { code: -1, message: 'CANVAS_EXEC_NOT_FOUND' } }),
    'GET /api/knowledge-base/list': ({ query }) => page(kbs, query.current, query.pageSize),
    'GET /api/knowledge-base/details': ({ query }) => {
      const k = kbs.find((x) => x.id === query.knowledgeBaseId);
      return k
        ? ok({ knowledgeBaseId: k.id, name: k.name, qaCount: k.qaCount, docCount: k.fileCount, webCount: k.pageCount, videoCount: k.videoCount, embeddingModel: k.modelType })
        : bad('knowledge base not found');
    },
    'GET /api/qa/metrics': ({ query }) => {
      const rows = state.faqs.filter((f) => f.kb === query.knowledgeBaseId);
      return ok({ total: rows.length, reviewed: rows.filter((f) => f.isReviewed).length, unreviewed: rows.filter((f) => !f.isReviewed).length });
    },
    'POST /api/qa/list': ({ body }) => {
      if (body.filterType === undefined || body.sortType === undefined) {
        return bad('filterType must be one of the following values: ALL, REVIEWED, GENERATED, 0, 1, 2');
      }
      if (!hasKb(body.knowledgeBaseId)) return bad('knowledge base not found');
      if (semanticFail && body.searchMode === 'semantic') return gateway;
      let rows = state.faqs.filter((f) => f.kb === body.knowledgeBaseId);
      if (typeof body.filterType === 'string') rows = rows.filter((f) => !f.isReviewed); // 真实服务端的坑：传字符串一律只回未审核的
      else if (body.filterType === 1) rows = rows.filter((f) => f.isReviewed);
      else if (body.filterType === 2) rows = rows.filter((f) => !f.isReviewed);
      let out = rows.map((f) => faqOut(f));
      if (body.sortType === 'SIMILARITY' && body.keyword) {
        out = body.searchMode === 'text'
          ? rows.filter((f) => f.question.includes(body.keyword) || f.answer.includes(body.keyword)).map((f) => faqOut(f))
          : semanticRows(rows, body.knowledgeBaseId, body.keyword, SEMANTIC_FLOOR).map(({ f, score }) => faqOut(f, { similarity: score }));
      }
      return page(out, body.current, body.pageSize);
    },
    'POST /api/qa/check-similarity': ({ body }) => (!hasKb(body.knowledgeBaseId) ? bad('knowledge base not found') : ok(state.faqs
      .filter((f) => f.kb === body.knowledgeBaseId)
      .map((f) => omit({ qaId: f.id, question: f.question, answer: f.answer, similarity: sim(body.question, f.question), reviewed: f.isReviewed, materials: [], mhMaterialIds: [] }))
      .filter((f) => f.similarity >= 0.5)
      .sort((a, b) => b.similarity - a.similarity))),
    'GET /api/knowledge-base/file/list': ({ query }) => page(
      filesOf(query.knowledgeBaseId).map((f) => ({ id: f.id, name: f.name, extension: f.extension, status: f.status, createAt: 0, createBy: 'u', tags: f.tags })),
      query.current, query.pageSize,
    ),
    'GET /api/knowledge-base/file/details': ({ query }) => {
      const f = state.files.find((x) => String(x.id) === String(query.docId) && x.kb === query.knowledgeBaseId);
      return f
        ? ok({ id: f.id, name: f.name, status: f.status, extension: f.extension, paragraphCount: parasOf(f.id).length, docUrl: docUrl(f), abstract: f.abstract, tags: f.tags })
        : bad('doc not found');
    },
    'GET /api/knowledge-base/file/paragraphs': ({ query }) => {
      if (!query.knowledgeBaseId) return bad('knowledgeBaseId must be a string');
      if (!/^\d+$/.test(String(query.id ?? ''))) return bad('id must be a number string');
      const rows = parasOf(query.id).map((p) => {
        if (p.status === 'processing' && p.readyAfter !== undefined) {
          p.seen = (p.seen ?? 0) + 1;
          if (p.seen >= p.readyAfter) p.status = 'ready';
        }
        const { fileId, readyAfter: _r, seen: _s, ...rest } = p;
        return { ...rest, createdAt: 0 };
      });
      return page(rows, query.current, query.pageSize);
    },
    'GET /api/knowledge-base/web/list': ({ query }) => page([], query.current, query.pageSize),
  };

  const writeRoutes = {
    'POST /api/qa/batch-create': ({ body }) => {
      if (!hasKb(body.knowledgeBaseId)) return bad('knowledge base not found');
      for (const q of body.qaList ?? []) {
        state.faqs.push({ id: state.nextFaqId++, kb: body.knowledgeBaseId, question: mangle(q.question), answer: mangle(q.answer), isReviewed: false });
      }
      return ok(null);
    },
    'POST /api/qa/batch-review': ({ body }) => {
      const rows = state.faqs.filter((f) => f.kb === body.knowledgeBaseId && body.ids.includes(f.id));
      if (rows.length !== body.ids.length) return bad('qa not found');
      rows.forEach((f) => { f.isReviewed = true; });
      return ok(null);
    },
    'POST /api/qa/batch-delete': ({ body }) => {
      state.faqs = state.faqs.filter((f) => !(f.kb === body.knowledgeBaseId && body.ids.includes(f.id)));
      return ok(null);
    },
    'POST /api/knowledge-base/file/manual-create': ({ body }) => {
      if (!hasKb(body.knowledgeBaseId)) return bad('knowledge base not found');
      state.files.push({ id: state.nextDocId++, kb: body.knowledgeBaseId, name: body.name, extension: '', status: 'ready', manual: true, tags: [], abstract: '', original: '' });
      return ok(null);
    },
    'POST /api/knowledge-base/file/manual-create-paragraph': ({ body }) => {
      const f = state.files.find((x) => x.id === body.docId && x.kb === body.knowledgeBaseId);
      if (!f) return bad('doc not found');
      state.paragraphs.push({ id: state.nextParaId++, fileId: f.id, index: parasOf(f.id).length, content: mangle(body.content), wordCount: [...body.content].length, status: 'processing', readyAfter });
      return ok(null);
    },
    'POST /api/knowledge-base/file/delete': ({ body }) => {
      const before = state.files.length;
      state.files = state.files.filter((f) => !(f.id === body.id && f.kb === body.knowledgeBaseId));
      if (state.files.length === before) return bad('doc not found');
      state.paragraphs = state.paragraphs.filter((p) => String(p.fileId) !== String(body.id));
      return ok(null);
    },
    'POST /api/knowledge-base/file/update-abstract': ({ body }) => {
      const f = state.files.find((x) => x.id === body.docId && x.kb === body.knowledgeBaseId);
      if (!f) return bad('doc not found');
      f.abstract = body.abstract;
      return ok(null);
    },
  };

  const all = { ...routes, ...(writable ? writeRoutes : {}) };
  // 按路由计数，第 n 次调用按 failOn 失败：数字是直接失败；{ n, applied: true } 是先写进去再失败（回复丢了）
  const wrapped = Object.fromEntries(Object.entries(all).map(([key, handler]) => [key, async (record) => {
    state.calls[key] = (state.calls[key] ?? 0) + 1;
    const rule = (failOn[key] ?? []).find((r) => (typeof r === 'number' ? r : r.n) === state.calls[key]);
    if (rule !== undefined) {
      if (typeof rule === 'object' && rule.applied) await handler(record);
      return gateway;
    }
    return handler(record);
  }]));
  const server = await startFakeMiaodong(wrapped);
  origin = server.origin;
  // 原文件下载：/files/<文件 id>/<文件名>，不看身份（对象存储上的公开地址）
  for (const f of state.files) registerDownload(server, state, f.id);
  const reads = new Set(Object.keys(routes));
  const writes = new Set(writable ? Object.keys(writeRoutes) : []);
  return Object.assign(server, {
    state,
    unexpected: () => server.requests.filter((r) => !reads.has(`${r.method} ${r.path}`) && !writes.has(`${r.method} ${r.path}`) && !r.path.startsWith('/files/')),
    writes: () => server.requests.filter((r) => writes.has(`${r.method} ${r.path}`)),
  });
}

function registerDownload(server, state, id) {
  const f = state.files.find((x) => x.id === id);
  server.routes[`GET /files/${id}/${encodeURIComponent(f.name)}`] = () => {
    const current = state.files.find((x) => x.id === id);
    return current ? { status: 200, headers: { 'Content-Type': 'application/octet-stream' }, body: current.original } : { status: 404, body: 'not found' };
  };
}
