// 秒懂知识库的读接口（spec 3a §2.1）。只读：这里没有任何写接口的封装。
// §2.2 的两个坑在这一层挡住：
// - FAQ 列表的 filterType 只传数字：传字符串时服务端一律只回未审核的，还不报错；
// - 列表和详情的字段名不一样（id / knowledgeBaseId、fileCount / docCount、pageCount / webCount），
//   相似度检查的 id 叫 qaId：这里统一成一套。
import { request } from './http.mjs';
import { asArray } from './api.mjs';

export const FAQ_FILTER = Object.freeze({ ALL: 0, REVIEWED: 1, PENDING: 2 });
// 服务端 pageSize 给到 500 都照给（spec §2.1，09-25）：取 200，2725 条的大库十几次请求读完
export const PAGE_SIZE = 200;
export const SEARCH_SIZE = 50;
const MAX_PAGES = 1000;

const str = (v) => (v === null || v === undefined ? '' : String(v));
const num = (v) => (v !== null && v !== '' && Number.isFinite(Number(v)) ? Number(v) : 0);

export function normalizeKb(raw) {
  return {
    id: str(raw?.id ?? raw?.knowledgeBaseId),
    name: str(raw?.name),
    faqCount: num(raw?.qaCount),
    fileCount: num(raw?.fileCount ?? raw?.docCount),
    webCount: num(raw?.pageCount ?? raw?.webCount),
    videoCount: num(raw?.videoCount),
    model: str(raw?.modelType ?? raw?.embeddingModel),
  };
}

export function normalizeFaq(raw) {
  return {
    id: num(raw?.id ?? raw?.qaId),
    question: str(raw?.question),
    answer: str(raw?.answer),
    reviewed: (raw?.isReviewed ?? raw?.reviewed) === true,
    generated: raw?.isAutogenerated === true,
    duplicateStatus: str(raw?.duplicateStatus) || 'normal',
    similarity: typeof raw?.similarity === 'number' ? raw.similarity : null,
  };
}

// 服务端可能把每页封顶在比 pageSize 小的条数：有 page.total 时按它判断读没读完，没有才看这一页满没满
async function allPages(fetchPage) {
  const rows = [];
  for (let current = 1; current <= MAX_PAGES; current++) {
    const { list, total } = await fetchPage(current);
    rows.push(...list);
    if (!list.length) break;
    if (Number.isFinite(total) && total > 0) {
      if (rows.length >= total) break;
    } else if (list.length < PAGE_SIZE) break;
  }
  return rows;
}
const pageOf = (payload) => ({ list: asArray(payload?.data), total: Number(payload?.page?.total) });

export async function listKbs(identity, orgId) {
  const rows = await allPages(async (current) => pageOf(await request(identity, '/api/knowledge-base/list', { query: { orgId, current, pageSize: PAGE_SIZE } })));
  return rows.map(normalizeKb).filter((k) => k.id);
}

export async function kbDetails(identity, orgId, kbId) {
  const payload = await request(identity, '/api/knowledge-base/details', { query: { orgId, knowledgeBaseId: kbId } });
  return normalizeKb(payload?.data ?? {});
}

export async function faqMetrics(identity, orgId, kbId) {
  const d = (await request(identity, '/api/qa/metrics', { query: { orgId, knowledgeBaseId: kbId } }))?.data ?? {};
  return { total: num(d.total), reviewed: num(d.reviewed), unreviewed: num(d.unreviewed) };
}

export async function listFaqs(identity, orgId, kbId, { filter = FAQ_FILTER.ALL } = {}) {
  const rows = await allPages(async (current) => pageOf(await request(identity, '/api/qa/list', {
    method: 'POST',
    query: { orgId },
    body: { knowledgeBaseId: kbId, current, pageSize: PAGE_SIZE, filterType: filter, sortType: 'DEFAULT' },
  })));
  return rows.map(normalizeFaq);
}

// 按相似度搜 FAQ。mode=semantic：语义搜索，分数就是大模型知识库工具的分数（spec §2.3），未审核的不在索引里，
// 而且只返回 0.8 以上的；mode=text：问题或答案里包含这段文字，未审核的也算
export async function searchFaqs(identity, orgId, kbId, text, { mode = 'semantic', size = SEARCH_SIZE } = {}) {
  const payload = await request(identity, '/api/qa/list', {
    method: 'POST',
    query: { orgId },
    body: { knowledgeBaseId: kbId, current: 1, pageSize: size, filterType: FAQ_FILTER.ALL, sortType: 'SIMILARITY', keyword: text, searchMode: mode },
  });
  return asArray(payload?.data).map(normalizeFaq);
}

// 问题对问题的相似度：未审核的也查得到（spec §2.3）
export async function checkSimilarity(identity, orgId, kbId, question) {
  const payload = await request(identity, '/api/qa/check-similarity', { method: 'POST', query: { orgId }, body: { knowledgeBaseId: kbId, question } });
  return asArray(payload?.data).map(normalizeFaq);
}

export async function listFiles(identity, orgId, kbId) {
  const rows = await allPages(async (current) => pageOf(await request(identity, '/api/knowledge-base/file/list', {
    query: { orgId, knowledgeBaseId: kbId, current, pageSize: PAGE_SIZE },
  })));
  return rows.map((f) => ({ id: num(f.id), name: str(f.name), extension: str(f.extension), status: str(f.status) }));
}

export async function fileDetails(identity, orgId, kbId, fileId) {
  const d = (await request(identity, '/api/knowledge-base/file/details', { query: { orgId, knowledgeBaseId: kbId, docId: fileId } }))?.data ?? {};
  return { id: num(d.id), name: str(d.name), status: str(d.status), paragraphCount: num(d.paragraphCount) };
}

// 段落列表：id 是文件的数字 id（以字符串传）；knowledgeBaseId 文档里漏写了，缺了回 400（spec §2.2 第 2 条）
export async function listParagraphs(identity, orgId, kbId, fileId) {
  const rows = await allPages(async (current) => pageOf(await request(identity, '/api/knowledge-base/file/paragraphs', {
    query: { orgId, knowledgeBaseId: kbId, id: String(fileId), current, pageSize: PAGE_SIZE },
  })));
  return rows.map((p) => ({ id: num(p.id), index: num(p.index), content: str(p.content), wordCount: num(p.wordCount), status: str(p.status) }));
}

export async function listWebs(identity, orgId, kbId) {
  const rows = await allPages(async (current) => pageOf(await request(identity, '/api/knowledge-base/web/list', {
    query: { orgId, knowledgeBaseId: kbId, current, pageSize: PAGE_SIZE },
  })));
  return rows.map((w) => ({ id: str(w.id), name: str(w.name ?? w.title), url: str(w.url), status: str(w.status) }));
}
